version: '3.8'

services:
  odoo:
    container_name: odoo
    build: .
    working_dir: /opt/odoo
    ports:
      - "8069:8069"
    volumes:
      - ./odoo:/opt/odoo
      - ./custom_modules:/mnt/extra-addons
      - ./conf/odoo.conf:/etc/odoo/odoo.conf
      - odoo_data:/var/lib/odoo
      - ./logs:/var/log/odoo
    restart: unless-stopped
    command: ["python", "odoo-bin", "-c", "/etc/odoo/odoo.conf"]
    networks:
      - odoo_network

volumes:
  odoo_data:

networks:
  odoo_network:
    driver: bridge