version: '3.8'

services:
  # Odoo Application
  odoo:
    build: .
    container_name: odoo_app
    environment:
      # Set your external database connection details here
      - HOST=primary.odoodb--q9b4md8jjy66.addon.code.run
      - USER=_6a1dd2fcee051634
      - PASSWORD=_184a51919caa8c9246a1eb078f8166
    volumes:
      # Mount the entire project directory (including odoo-bin)
      - .:/opt/odoo
      # Mount configuration file
      - ./conf/odoo.conf:/etc/odoo/odoo.conf
      # Mount data directory for file storage
      - odoo_data:/var/lib/odoo
      # Mount logs
      - ./logs:/var/log/odoo
    ports:
      - "8069:8069"
    restart: unless-stopped
    network_mode: host  # Use host network to access external database

volumes:
  odoo_data: