services:
  # Odoo Application
  odoo:
    build: .
    container_name: odoo_app
    environment:
      # Set your external database connection details here
      - HOST=your_db_host
      - USER=your_db_user
      - PASSWORD=your_db_password
    volumes:
      # Mount your local Odoo source code
      - ./odoo:/opt/odoo/odoo
      # Mount configuration file
      - ./config/odoo.conf:/etc/odoo/odoo.conf
      # Mount custom addons
      - ./addons:/mnt/extra-addons
      # Mount data directory for file storage
      - odoo_data:/var/lib/odoo
      # Mount logs
      - ./logs:/var/log/odoo
    ports:
      - "8069:8069"
    restart: unless-stopped
    network_mode: host  # Use host network to access external database

volumes:
  odoo_data: