services:
  odoo:
    container_name: odoo
    build: .
    networks:
      - odoo_network
    ports:
      - "8069:8069"
    volumes:
      - "./odoo:/opt/odoo"
      - "./custom_modules:/mnt/extra-addons"
      - "./conf:/etc/odoo"
      - "odoo_data:/var/lib/odoo"
    restart: always
    command: ["python", "odoo-bin", "-c", "/etc/odoo/odoo.conf", "-i", "base"]

volumes:
  odoo_data:

networks:
  odoo_network:
    driver: bridge